// Generated by Wrangler by running `wrangler types worker-configuration.d.ts`

interface Env {
	avatars: KVNamespace;
	BLUESKY_CDN: "https://cdn.bsky.app";
	BLUESKY_GET_PROFILE: "https://public.api.bsky.app/xrpc/app.bsky.actor.getProfile";
	CACHE_EXPIRY_TTL: 300;
	README_REDIRECT: "https://github.com/prompt/avatars.dog";
}
